Added filter process

diff --git a/src/main b/src/main
--- a/src/main
+++ b/src/main
@@ -20,6 +20,10 @@ source "$UTILS_DIR/check"
 # shellcheck disable=SC1091
 source "$UTILS_DIR/fetcher"
 
+# shellcheck disable=SC1091
+source "$UTILS_DIR/filter"
+
+
 function getArgs() {
 	while [[ $# -gt 0 ]]; do
 		case "$1" in
@@ -36,8 +40,6 @@ function getArgs() {
     --fix-dependencies)
 			VERBOSE=true
       fixDep
-			shift
-			exit
 			;;
 
 		-h | --help)
@@ -107,6 +109,7 @@ fixDep() {
 	else
 		echo "Unknown Distro"
 	fi
+  #shellcheck disable=SC2181
 	if [ $? -eq 0 ]; then
 		log "Successfully installed dependencies"
     exit
@@ -114,7 +117,6 @@ fixDep() {
 		flog "Failed to install dependencies"
 		exit 1
 	fi
-  exit
 }
 
 
@@ -138,11 +140,20 @@ main() {
 	getArgs "$@"
 	performChecks
 	getFullDataJson
+  filterDATA
+  if isJson "$FILTERED_DATA"; then
+    log "$(ok "Filtered data successfully")"
+  else
+    flog "$(err "Filtered data is invalid\nCheck Logs $LOG_DIR/$LOG_FILE")"
+    exit 1
+  fi
+  FINAL_DATA="{\"unfiltered\":$JSON_DATA,\"filtered\":$FILTERED_DATA}"
+  log ""
 	log ":: Testing JSON data integrity"
-	if isJson "$JSON_DATA"; then
+	if isJson "$FINAL_DATA"; then
 		log "$(ok "Generated a valid JSON data")"
 		# shellcheck disable=SC2005
-		echo "$(echo "$JSON_DATA" | jq)" >"$PROJECT_ROOT/data.json"
+		echo "$(echo "$FINAL_DATA" | jq)" >"$PROJECT_ROOT/data.json"
 	else
 		flog "$(err "Generated JSON data is invalid\nCheck Logs $LOG_DIR/$LOG_FILE")"
 		exit 1
diff --git a/src/utils/fetcher b/src/utils/fetcher
--- a/src/utils/fetcher
+++ b/src/utils/fetcher
@@ -101,5 +101,11 @@ function getFullDataJson() {
 
 	log ""
 	log ":: Compiling all data in one json"
-	JSON_DATA="$JSON_DATA}"
+	JSON_DATA="{\"raw\":$JSON_DATA}}"
+  if isJson "$JSON_DATA"; then
+    log "$(ok "Compiled Successfully")"
+  else
+    flog "$(err "Generated JSON data is invalid\nCheck Logs $LOG_DIR/$LOG_FILE")"
+    exit 1
+  fi
 }
